version: '3.9'

services:
#  exeat.boilerplate-service:
#    container_name: 'exeat.boilerplate-service'
#    build: .
#    ports:
#      - "3000:3000"
#    links:
#      - mongodb
#    depends_on:
#      - mongodb
#    environment:
#      - APP_ENV=PREPROD
#      - DB_HOST=mongodb
#      - DB_PORT=27017
#      - DB_NAME=exeat
  mongodb:
    container_name: 'mongodb'
    image: mongo:latest
    ports:
      - "64000:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=exeat

volumes:
  mongo_data: {}
